### ISSUE TITLE
Settings form does not select selected options

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/citationStyleLanguage#21] opened 2018-02-07 13:54 UTC
I just noticed that when I load the settings form of the plugin, the form does not set the selected _Primary Citation Format_ option as selected. It's the same for _Additional Citation Formats_ and _Downloadable Formats_.

I saw this on an Open Journal Systems 3.1.0.1 installed from the .tar.gz
It looked at it on a FireFox 52.5.3 (32-Bit) (Windows) and Google Chrome (Version 62.0.3202.89 (64-Bit))

**Comment by NateWr** [comment] 2018-02-07 16:16
I believe this was fixed in a commit on Jan 10 related to the new SelectListHandlers: https://github.com/pkp/citationStyleLanguage/commit/66984f7f45841ab7bf853a238d93399c3199b7be

I'm unable to reproduce with current `master` but if you can let us know.

**Closed by NateWr** 2018-02-07 16:16 UTC
